module QuestionStore exposing (allQuestions)

import Question exposing (AnswerClass(..), Question)
import Set exposing (Set)


allQuestions : List Question
allQuestions =
    List.concat [ randomQuestions, locationQuestions, verbQuestions ]


randomQuestions =
    List.map (\( hanguel, phonetic ) -> Question hanguel (JustPronunciation phonetic) (Set.fromList [ "Random" ]))
        [ ( "가다", "ka-ta" )
        , ( "개", "kae" )
        , ( "공부", "kong-bu" )
        , ( "과일", "kwa-il" )
        , ( "학교", "hak-kyo" )
        , ( "나", "na" )
        , ( "농구", "nong-ku" )
        , ( "저녁", "cheo-nyeo(k)" )
        , ( "운동", "un-tong" )
        , ( "두부", "tu-bu" )
        , ( "돈", "ton" )
        , ( "돼지", "twae-chi" )
        , ( "걷다", "kot-ta" )
        , ( "라면", "ra-myeon" )
        , ( "런던", "reon-teon" )
        , ( "둘", "tul" )
        , ( "달력", "tal-lyeo(k)" )
        , ( "모자", "mo-cha" )
        , ( "물", "mul" )
        , ( "뭐", "mweo" )
        , ( "곰", "kom" )
        , ( "바다", "ba-ta" )
        , ( "불", "bul" )
        , ( "별", "byeol" )
        , ( "덥다", "top-ta" )
        , ( "사과", "sa-gwa" )
        , ( "신발", "sin-bal" )
        , ( "쇠", "swae" )
        , ( "맛", "ma(t)" )
        , ( "아기", "a-gi" )
        , ( "언제", "eon-chae" )
        , ( "약", "ya(k)" )
        , ( "공", "kong" )
        , ( "주말", "chu-mal" )
        , ( "중국", "chung-kuk" )
        , ( "쥐", "chwi" )
        , ( "낮", "na(t)" )
        , ( "차", "tcha" )
        , ( "춤", "tchum" )
        , ( "최고", "chwae-go" )
        , ( "몇", "myeo(t)" )
        , ( "컵", "keop" )
        , ( "코", "ko" )
        , ( "퀴즈", "kwi-cheu" )
        , ( "부엌", "bu-eok" )
        , ( "토요일", "toh-yo-il" )
        , ( "털", "teohl" )
        , ( "튀김", "twhi-gim" )
        , ( "밭", "ba(t)" )
        , ( "피", "pi" )
        , ( "팔", "pal" )
        , ( "편지", "peyon-chi" )
        , ( "앞", "ap" )
        , ( "호주", "ho-chu" )
        , ( "한국", "han-gu(k)" )
        , ( "형", "hyeong" )
        , ( "좋다", "cho(t)-ta" )
        , ( "꼬리", "kko-li" )
        , ( "낚시", "na(k)-shi" )
        , ( "또", "tto" )
        , ( "뛰다", "kwi-ta" )
        , ( "빵", "bbang" )
        , ( "쓰다", "sseu-ta" )
        , ( "맛있다", "ma(t)-i(t)-ta" )
        , ( "찌게", "cchi-gae" )
        , ( "이데일리", "i-tae-il-li" )
        ]


locationQuestions =
    List.map (\( hanguel, english ) -> Question hanguel (JustEnglish english) (Set.fromList [ "Location" ]))
        [ ( "우체국", "post office" )
        , ( "기숙사", "dormitory" )
        , ( "책방", "book store" )
        , ( "위", "above" )
        , ( "아래", "below" )
        , ( "뒤", "behind" )
        , ( "식당", "restaurant" )
        , ( "학교", "school" )
        ]


verbQuestions =
    List.map (\( hanguel, english ) -> Question hanguel (JustEnglish english) (Set.fromList [ "Verb" ]))
        [ ( "있어요", "exists/is there" )
        , ( "어때요", "is how" )
        , ( "좋아요", "is good, nice" )
        , ( "나빠요", "is bad" )
        , ( "괜찮아요", "is okay/not bad" )
        , ( "맛있어요", "is delicious" )
        , ( "맛없어요", "tastes bad" )
        , ( "커요", "is big" )
        , ( "많아요", "is much/many" )
        , ( "싸요", "is cheap" )
        , ( "넓어요", "is spacious" )
        , ( "읽어요", "read" )
        , ( "숙제해요", "do homework" )
        , ( "샤워해요", "have a shower" )
        , ( "작아요", "is small" )
        , ( "없어요", "do not have" )
        , ( "봐요", "see" )
        , ( "사랑해요", "love" )
        , ( "써요", "use" )
        , ( "예뻐요", "is pretty" )
        , ( "전화해요", "call/phone" )
        , ( "먹어요", "eat" )
        , ( "마셔요", "drink" )
        , ( "공부해요", "study" )
        , ( "자요", "sleep" )
        , ( "앉아요", "sit down" )
        , ( "비싸요", "is expensive")
        ]
